### ISSUE TITLE
Two new properties for `iTheme` type

### ISSUE THREAD

**Issue by pkreipke** [dantasfiles/AmplifyReactNativeTypes#1]
Thank you for this types file! Very helpful.

When I just used `import { AmplifyTheme } from 'aws-amplify-react-native'` and inspected the AmplifyTheme it contains two new theme properties.

```
	signedOutMessage: {};
	sectionFooterLinkDisabled: {};
```

Examples:
`signedOutMessage` is the message at the bottom of the screen.
`sectionFooterLinkDisabled` is the style of the "Resend Code" link in the confirm code screen when inactive.

I was able to successfully override and use them.

Can also see them (and a few others) here: https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react-native/src/AmplifyTheme.ts

Regards,
Per

**Comment by dantasfiles** [comment]
Thanks!
